### ISSUE TITLE
Woweb Github + bucket voor component library

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/component-library-infra#1]
Woweb is bezig met het verhuizen van de component library naar gemeente Nijmegen GitHub. De repository bestaat (https://github.com/GemeenteNijmegen/component-library ) en woweb heeft toegang (mogelijk niet genoeg om actions te bouwen?).

Zij gaan:
- de gitlab CI ombouwen naar GitHub actions
- Zorgen dat het resultaat daarvan naar een S3-bucket kan.
Dit staat gepland voor week 22.

Wij zorgen:
- voor die bucket. Daaromheen bouwen we een nieuw CDK-project voor de infra om de component library als statische site aan te bieden.

Todo:
- [x] CDK-project voor infra: https://github.com/GemeenteNijmegen/component-library-infra
- [ ] #2
- [ ] #3

**Comment by joostvanderborg** [comment]
Repo is aangemaakt (https://github.com/GemeenteNijmegen/component-library-infra). Account in dev-omgeving wordt nu geprovisioned (gn-component-library-development)

**Comment by wvdeeckhout** [comment]
@joostvanderborg gaat deze aanpassen

**Comment by joostvanderborg** [comment]
Dit issue is opgesplitst + in de epic (https://github.com/GemeenteNijmegen/devops/issues/55) opgenomen.
