### ISSUE TITLE
Content-Security-Policy uitbreiden

### ISSUE THREAD

**Issue by Michel-Verhoeven** [GemeenteNijmegen/component-library-infra#254]
**Probleem**
Voorbeeld afbeeldingen vanaf https://mdbootstrap.com/ worden niet getoond.
![Scherm­afbeelding 2024-05-29 om 14 34 55](https://github.com/GemeenteNijmegen/component-library/assets/79970817/12bdae67-6e64-479b-a27a-186d1f212a98)

**Oorzaak**
De response header van iedere pagina bevat in de Content-Security-Policy `img-src 'self'`
![Scherm­afbeelding 2024-05-29 om 14 35 02](https://github.com/GemeenteNijmegen/component-library/assets/79970817/b71358c4-ff29-4cf7-b042-bcf92855a9b0)

**Oplossing**
img-src in de Content-Security-Policy uitbreiden met de mdbootstrap.com verwijzing. `img-src 'self' https://mdbootstrap.com`

**Comment by joostvanderborg** [comment]
Opgelost in #257
